- name: Copy iptables config
  template:
    src: proxy_iptables_save
    dest: /etc/iptables/rules.v4
  register: iptables_config

- name: Copy ip6tables config
  template:
    src: proxy_ip6tables_save
    dest: /etc/iptables/rules.v6
  register: ip6tables_config

- name: Apply ip{,6}tables rules
  shell: |
    iptables -F
    ip6tables -F
    iptables-restore < /etc/iptables/rules.v4
    ip6tables-restore < /etc/iptables/rules.v6
  when: iptables_config.changed or ip6tables_config.changed

- name: Copy sshd config
  template:
    src: sshd_config
    dest: /etc/ssh/sshd_config
  register: sshd_config

- name: Restart sshd
  systemd:
    service: sshd
    state: restarted
  when: sshd_config.changed

- name: Add jump user
  user:
    name: jump
    uid: 1001
    shell: /usr/sbin/nologin
    password: "U6aMy0wojraho"  # Empty password hash

- name: Generate an OpenSSH keypair
  community.crypto.openssh_keypair:
    path: /root/.ssh/jump_server
    type: ed25519

- name: Add apt repo for kangaroo
  apt_repository:
    repo: deb [trusted=yes] https://repo.hamptonmoore.com/apt /
    state: present

- name: Install kangaroo
  apt:
    update_cache: yes
    install_recommends: false
    pkg:
      - kangaroo

- name: Copy kangaroo config
  template:
    src: kangaroo.conf
    dest: /etc/kangaroo.conf
  register: sshd_config

- name: Add kangaroo service
  template:
    src: kangaroo.service
    dest: /lib/systemd/system/kangaroo.service
    owner: root
    group: root
  register: kangaroo_service 

- name: Start and enable kangaroo 
  systemd:
    name: kangaroo
    daemon-reload: true
    enabled: true
    state: started
  when: kangaroo_service.changed